### ISSUE TITLE
Feature request: Message edit/delete logging

### ISSUE THREAD

**Issue by ZeNyfh** [9382/Talk-Bot#19]
Title self explanatory, add logging for message edits and deletions.

> preferred format for deletions:

**Message deleted in #CHANNEL**
USERNAME#TAG (USERID)

**ID:**
MESSAGEID

**Message content:**
MESSAGECONTENT

> preferred format for edits:

**Message edited in #CHANNEL**
USERNAME#TAG (USERID)

**ID:**
MESSAGEID

**Old message content:**
OLDMESSAGECONTENT

**New message content:**
NEWMESSAGECONTENT

Unsure if this is in the works or not, good to put it here anyways

**Comment by 9382** [comment]
See 767d7f5
