### ISSUE TITLE
message log doesnt recognise links

### ISSUE THREAD

**Issue by ZeNyfh** [9382/Talk-Bot#22]
![image](https://user-images.githubusercontent.com/66276905/154212018-ae426fc1-701f-4bee-bf2b-98795ec7e877.png)
"it doesnt recognize links even when theyre pasted as text as part of the message"

**Comment by 9382** [comment]
Im not entirely sure about the "Even when pasted as text" part of it, but i will keep attempting to replicate this myself, as im aware files uploaded dont have their links noted

**Comment by 9382** [comment]
(the help wanted is for finding the cause of the issue directly - its very ambiguous rn)

**Comment by ZeNyfh** [comment]
i mean, just managed to recreate this issue
![image](https://user-images.githubusercontent.com/66276905/155910717-e9ca27a4-894b-4e14-b009-0c5092719eee.png)
it just completely didnt log the message with the link first thing in the message, but logged it when the link was not the first thing in the message:
![image](https://user-images.githubusercontent.com/66276905/155910773-4d0218ff-213b-4163-89cd-f9a5a04e6fc9.png)

**Comment by 9382** [comment]
that first screenshot just makes it even more confusing - the administrator bot doesnt get the link either? which am i meant to pay attention to, this makes no sense

**Comment by ZeNyfh** [comment]
admin logs it at 1:39, talk bot doesn't.

admin logs new message (test) at 1:40, talk bot does as well

2nd screenshot:

talk bot logs link if text is before it (from what im seeing), admin logs it fine again

**Comment by 9382** [comment]
To clarify: Its not links that are the issue, its files uploaded directly along with it (or most likely anyways)

**Comment by 9382** [comment]
Fixed
